### PR TITLE
Add documentation and unit tests for Markdown code blocks

### LINKED ISSUE #220: Document how to test Markdown documents
I can't work out how to test code inside Markdown files. Currently the plugin does not ignore the markup needed to wrap code snippets in Markdown, i.e. something like

````text
```python
>>> print('Hi')
Hi
```
````

will fail because the final triple-backtick is assumed to be part of the output. Adding an extra blank line is not an option because it changes the final output.

(Also, the only documentation on how to pick up markdown files is [in the `tests` directory](https://github.com/scientific-python/pytest-doctestplus/blob/45fc0e989614728415d3bed9f7f2f25d4834e73a/tests/test_doctestplus.py#L583), could this be added to the README too?)

### PR DESCRIPTION
**Pull request by lpsinger**
Fixes #220.

### CODE REVIEW

**Review by pllim — APPROVED** [review]
Thanks! 

I never run this on Markdown so I have a newbie question, why "pycon" and not "python"? I associate "pycon" with the conference, not the language. 😸 

I won't merge yet in case @bsipocz wants to review.

**Comment by drammock** [comment]
> why "pycon" and not "python"?

@pllim think "Python Console" and it's easier to remember.

**Review by bsipocz — APPROVED** [review]

**Comment by bsipocz** [comment]
Thank you @lpsinger!

**Comment by pllim** [comment]
FWIW at least on GitHub, I still find "python" nicer than "pycon" even with the console stuff. Am I using it wrong?

### python

```python
>>> import numpy as np
>>> from astropy.table import QTable
>>> c = QTable.Column(np.array([1,2,3]), unit=u.mas / u.yr, name='c')
>>> d = QTable.Column(np.array([4,5,6]), unit=u.mas, name='d')
>>> c / d
<Column name='c' dtype='float64' unit='mas / yr' length=3>
0.25
 0.4
 0.5
>>> c.data / d.data
array([0.25, 0.4 , 0.5 ])
>>> c.unit / d.unit
Unit("1 / yr")
```

### pycon

```pycon
>>> import numpy as np
>>> from astropy.table import QTable
>>> c = QTable.Column(np.array([1,2,3]), unit=u.mas / u.yr, name='c')
>>> d = QTable.Column(np.array([4,5,6]), unit=u.mas, name='d')
>>> c / d
<Column name='c' dtype='float64' unit='mas / yr' length=3>
0.25
 0.4
 0.5
>>> c.data / d.data
array([0.25, 0.4 , 0.5 ])
>>> c.unit / d.unit
Unit("1 / yr")
```

**Comment by lpsinger** [comment]
> FWIW at least on GitHub, I still find "python" nicer than "pycon" even with the console stuff. Am I using it wrong?

You do you, @pllim :-)

I think it's rendering the `>>>` as operators.

**Pull request merged**
