### PR TITLE
MNT: consider_namespace_packages now required for pytest 8.2 or after

### LINKED ISSUE #240: TypeError: import_path() missing 1 required keyword-only argument: 'consider_namespace_packages' (pytest 8.2.dev)
New failures caused by pytest-dev (post pytest 8.1):

```
pytest_doctestplus/plugin.py:268: in collect
    module = import_path(fspath, mode=mode, root=self.config.rootpath)
E   TypeError: import_path() missing 1 required keyword-only argument: 'consider_namespace_packages'
```

Caused by:

* https://github.com/pytest-dev/pytest/pull/11997

### PR DESCRIPTION
**Pull request by pllim**
Fix #240

### CODE REVIEW

**Comment by pllim** [comment]
After this is merge, should rerun CI over at https://github.com/astropy/pytest-filter-subpackage/ to make sure its devdeps is green too.

**Review by bsipocz — APPROVED** [review]
Thanks @pllim!

**Comment by pllim** [comment]
I see that you already reran pytest-filter-subpackage CI and it is green now. Thanks a lot!

**Comment by bsipocz** [comment]
I ended up changing the changelog for this PR in the new v1.2.1 release as I'm sure there'll be more breakage from 8.2....

**Pull request merged**
