### PR TITLE
Precautionary init for OutputChecker

### PR DESCRIPTION
**Pull request by matthew-brett**
CPython source has no __init__ for this class, but just in case, and to
reassure readers.

https://github.com/python/cpython/blob/main/Lib/doctest.py#L1609

### CODE REVIEW

**Review by pllim — COMMENTED** [review]
I don't know how I feel about inserting unnecessary constructor call.

Do they have plans to add init after so long without? Surely that would be announced in change log?

**Comment by matthew-brett** [comment]
I could replace with a comment to remember to check the CPython change log in case they introduce an `__init__`?

**Review by bsipocz — COMMENTED** [review]
I would say go ahead with this one, if it fails as they add one, we'll notice when we add a new python version  support. 

However, if they add one, and we don't have this, we won't notice automatically (and we may want to use that init).

**Review by pllim — APPROVED** [review]
Okay, then. Thanks everyone!

**Pull request merged**
