### PR TITLE
MAINT: No need for weekly dependabot

### PR DESCRIPTION
**Pull request by bsipocz**
No need for weekly updates from dependabot, monthly is more than enough here.

cc @pllim as you added the original configs.

### CODE REVIEW

**Review by pllim — APPROVED** [review]
Works for me. Thanks!

**Comment by pllim** [comment]
Ah interesting. Did you set it up to auto delete branch on merge? Pretty nifty!

**Comment by pllim** [comment]
Where is the setting? I am interested! 😆

**Comment by bsipocz** [comment]
DM-ed you the screenshots

**Pull request merged**
