### PR TITLE
MAINT: fix pytest 8.0dev compatibility

### LINKED ISSUE #212: BUG: incompatibility with pytest 8.0dev
New failures due to https://github.com/pytest-dev/pytest/pull/11268, but I haven't yet looked into solutions yet.

https://github.com/scientific-python/pytest-doctestplus/actions/runs/5814842359

```
 ==================================== ERRORS ====================================
________________________ ERROR collecting test session _________________________
../../.tox/py312-test-pytestdev/lib/python3.12/site-packages/_pytest/runner.py:340: in from_call
    result: Optional[TResult] = func()
../../.tox/py312-test-pytestdev/lib/python3.12/site-packages/_pytest/runner.py:371: in <lambda>
    call = CallInfo.from_call(lambda: list(collector.collect()), "collect")
../../.tox/py312-test-pytestdev/lib/python3.12/site-packages/_pytest/main.py:756: in collect
    for x in self._collectfile(path):
../../.tox/py312-test-pytestdev/lib/python3.12/site-packages/_pytest/main.py:605: in _collectfile
    if ihook.pytest_ignore_collect(collection_path=fspath, config=self.config):
../../.tox/py312-test-pytestdev/lib/python3.12/site-packages/_pytest/config/compat.py:66: in fixed_hook
    return hook(**kw)
../../.tox/py312-test-pytestdev/lib/python3.12/site-packages/pluggy/_hooks.py:433: in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
../../.tox/py312-test-pytestdev/lib/python3.12/site-packages/pluggy/_manager.py:112: in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
../../.tox/py312-test-pytestdev/lib/python3.12/site-packages/pytest_doctestplus/plugin.py:512: in pytest_ignore_collect
    collect_ignore = config._getconftest_pathlist("collect_ignore",
E   TypeError: Config._getconftest_pathlist() got an unexpected keyword argument 'rootpath'
=========================== short test summary info ============================
```

### PR DESCRIPTION
**Pull request by bsipocz**
To fix #212 (which has more info and reference links)

### CODE REVIEW

**Review by pllim — APPROVED** [review]
The diff didn't show L519. I thought I was going crazy. Haha. Thanks!

But I won't merge yet in case you are waiting for Simon to review.

**Comment by bsipocz** [comment]
I only pinged him as he did the previous 7.0+ fix. But either case I'm about to head home and won't cut a release today so merging can wait.

**Comment by pllim** [comment]
He does know the code better than I do, so I'll leave it to y'all good judgement. Thanks!

**Review by nicoddemus — APPROVED** [review]
The change seems reasonable, thanks for the fix and sorry for the breaking. 👍

**Pull request merged**
